apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-to-frontend
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: frontend
  ingress:
    # Allow traffic from pods in the database namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: database-namespace
  egress:
    # Allow traffic to pods in the database namespace
    - to:
        - namespaceSelector:
            matchLabels:
              name: database-namespace
  policyTypes:
    - Ingress
    - Egress
