# Jenkins master node can only communicate with necessary services and block all other traffic

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jenkins-master-isolation
  namespace: cicd
spec:
  podSelector:
    matchLabels:
      app: jenkins-master
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: jenkins-agent
    - podSelector:
        matchLabels:
          app: artifact-repo
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: jenkins-agent
    - podSelector:
        matchLabels:
          app: artifact-repo
    ports:
    - protocol: TCP
      port: 8080
