# Each stage is isolated and can only interact with necessary resources

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deploy-stage-isolation
  namespace: cicd
spec:
  podSelector:
    matchLabels:
      stage: deploy # prod env
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: artifact-repo
    ports:
    - protocol: TCP
      port: 8080 # Pull deployment packages
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: production-environment
    ports:
    - protocol: TCP
      port: 80 # Deploy to production environment
