# Allow only the vulnerability scanning tools within the pipeline to have access to the internet to download updated vulnerability databases.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vulnerability-scanner-restrictions
  namespace: cicd
spec:
  podSelector:
    matchLabels:
      app: vulnerability-scanner
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
